name: auto update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: git config
        run: |
          git config user.name "github-action"
          git config user.email "github-action@github.com"
      - name: setup scoop
        run: |
          iwr -useb get.scoop.sh | iex
          echo "~\\scoop\\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "~\\scoop\\apps\\scoop\\current\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: update bucket
        run: |
          auto-pr.ps1 -Upstream rkobayashi/scoop-mybucket:master -Dir . -Push
